 


drop database dronedb;


create database dronedb;
use dronedb;

CREATE TABLE SENSORS (
	ID Integer NOT NULL UNIQUE,
    SEN_NAME Char(30) NOT NULL,
    CONSTRAINT SENSORS_PK PRIMARY KEY (ID)
    );
    
    /* See TIVA board c file defines */
	INSERT INTO SENSORS VALUES (1, "Temperature");
	INSERT INTO SENSORS VALUES (2, "Pressure");
	INSERT INTO SENSORS VALUES (3, "xMagnetic");
	INSERT INTO SENSORS VALUES (4, "yMagnetic");
	INSERT INTO SENSORS VALUES (5, "zMagnetic");
	INSERT INTO SENSORS VALUES (6, "xAcc");
	INSERT INTO SENSORS VALUES (7, "yAcc");
	INSERT INTO SENSORS VALUES (8, "zAcc");

CREATE TABLE SEN_TIME (
	ID Integer NOT NULL AUTO_INCREMENT,
    SEN_ID			Integer		NOT NULL, 
    SEN_TIME	Char(50)	NOT NULL,
    CONSTRAINT	SEN_TIME_PK	 PRIMARY KEY (ID),
    CONSTRAINT SEN_TIME_FK FOREIGN KEY (SEN_ID) REFERENCES SENSORS (ID)
	);
    
Create TABLE SEN_DATA (
	TIME_ID Integer NOT NULL,
    ARRAY_INDEX Integer NOT NULL,
    
    SEN_DATA	Integer	NOT NULL,
    CONSTRAINT	SEN_DATA_PK	 PRIMARY KEY (TIME_ID, ARRAY_INDEX),
    CONSTRAINT SEN_DATA_FK FOREIGN KEY (TIME_ID) REFERENCES SEN_TIME (ID)
    );
    
Create TABLE SEN_CALC (

	TIME_ID Integer     NOT NULL,
    
    SEN_CALC DOUBLE PRECISION 	NOT NULL,
    

    ARRAY_INDEX Integer NOT NULL,
    SEN_TIME	Char(50)	NOT NULL,
    
    Units Char(30) not null,
    CONSTRAINT	SEN_CALC_PK	 PRIMARY KEY (TIME_ID,ARRAY_INDEX, SEN_TIME),
    
    CONSTRAINT SEN_CALC_FK FOREIGN KEY (TIME_ID) REFERENCES SEN_TIME (ID)
    
    
);